### PR TITLE
Awiye dev

### PR DESCRIPTION
**Pull request by emdes12**
created a new branch as the previous branch is having conflict with main, I decided to created a new branch which is upto date with the main and my previous branch, Thanks Top Universe, at least I cant solve conflict now

### CODE REVIEW

**Comment by emdes12** [comment]
@solomonmarvel97 please your review is needed on this soon , I have been delaying other with this my work

**Comment by solomonmarvel97** [comment]
I see you did a pull. Please test your code first. It looks like you forced the pull and it created some bugs in the codebase. Kindly check the screenshot i shared with you on discord.

**Comment by emdes12** [comment]
@solomonmarvel97 I have test and nothing its not work (the pages are not showing) but have fix that any other thing

**Review by emdes12 — COMMENTED** [review]
changes have been merged on affected  files

**Review by solomonmarvel97 — APPROVED** [review]

**Pull request merged**
