### PR TITLE
added the update profile page and make a component for the header …

### PR DESCRIPTION
**Pull request by emdes12**
… for the header nav (mobile-view) am still fixing something in it i will update it soon Sir and for the library for list of country but Sir @solomonmarvel97  your help is needed on this library, the countries are showing but the state are not.

### CODE REVIEW

**Comment by solomonmarvel97** [comment]
We can implement that together

**Comment by emdes12** [comment]
Thanks Sir, and you also promise to teach us how to test API

**Comment by solomonmarvel97** [comment]
This pull request has some merge conflicts. Please resolve them and make another pull request. Thanks

**Comment by emdes12** [comment]
Yes sir, that's the authentication you did, will fix it and make a new pull request soon

**Comment by solomonmarvel97** [comment]
This PR has merge conflicts. Please resolve them

**Comment by emdes12** [comment]
i made a new pull request on sunday but don't reflect, may be i should delete this pull request and make a new one

**Pull request closed without merging**
