### PR TITLE
I resolved issues affecting the faculty page layout

### PR DESCRIPTION
**Pull request by Yemihunter**
Faculty profile layout for web and mobile is resolved and responsive. I also made some adjustments to the nav bar.

### CODE REVIEW

**Comment by emdes12** [comment]
Will done boss

**Review by Yemihunter — COMMENTED** [review]
The faculty profile some style conflict which now resolved. 100% width and position fixed was added to the nav bar.

**Comment by emdes12** [comment]
Sorry, what of the upload and preview for the picture

**Comment by Yemihunter** [comment]
> Sorry, what of the upload and preview for the picture

we would work on that in vue

**Review by solomonmarvel97 — APPROVED** [review]

**Pull request merged**
